# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Data 100
description: Principles and Techniques of Data Science
author: Andrew Lenz
baseurl: '/sp22' # the subpath of your site, e.g. /blog
url: 'https://ds100.org' # the base hostname & protocol for your site, e.g. http://example.com

# Theme settings
remote_theme: pmarsceill/just-the-docs@v0.2.5-release
color_scheme: light
search_enabled: true
permalink: pretty
nav_links:
  Links:
    Course FAQ:
      - 'https://ds100.org/sp22faq'
    Datahub:
      - 'https://data100.datahub.berkeley.edu'
    Gradescope:
      - 'https://www.gradescope.com/courses/353100'
    Ed:
      - 'https://edstem.org/us/courses/15436/'

aux_links:
  # 'Kevin Lin':
  #   - 'https://kevinl.info'
  # 'Just the Class on GitHub':
  #   - 'https://github.com/kevinlin1/just-the-class'
footer: >-
  Powered by <a href="https://github.com/kevinlin1/just-the-class">Just the Class</a>

# Collections for website data
collections:
  - modules
  - announcements
  - staffers
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
